### ISSUE TITLE
Gutenberg Support

### ISSUE THREAD

**Issue by kroppenstedt** [palasthotel/wp-additional-authors#2]
@EdwardBock plz add Gutenberg support

See React-Error Log in Console.

**Comment by arnalyse** [comment]
Currently it's `meta-box.jsx` throwing the error, [on line 17](https://github.com/palasthotel/wp-additional-authors/blob/master/js/src/meta-box/meta-box.jsx#L17):

```
TypeError: _this._main_user_select is null
```

**Comment by EdwardBock** [comment]
Is fixed with version 1.1.1
