### ISSUE TITLE
Update from v1.1 to 1.14 breaks

### ISSUE THREAD

**Issue by greatestview** [palasthotel/wp-additional-authors#5]
Just tried to update the plugin to version 1.14 from version 1.1. Previously saved additional authors don’t appear anymore. After digging into the code I found out that the new version uses a separate database table while the old version uses the wp_postmeta table. So data is not lost but not accessible by the plugin anymore. Maybe we need a data migration here?

**Comment by EdwardBock** [comment]
@greatestview 

There is a [migration path](https://github.com/palasthotel/wp-additional-authors/blob/master/inc/update.php) that seems not work with your instance. I tried it with the same project just a minute ago and had no problems. Let's have a look at this together.

**Comment by greatestview** [comment]
Works! Some old tables in our database messed that update up. Reminder: Always work with fresh databases…
